name: dartedb
description: Dart Embedded Database.
version: 0.0.1
homepage: https://github.com/DevAlves1993/Dartedb
author: Christian Amani <alvesamani@gmail.com>

environment:
  sdk: ^1.23.0

dependencies:
  logging: ^0.11.3+1


dev_dependencies:
  test: ^0.12.20+13
